<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\IBMPlexMono-Regular.ttf" />
    <None Remove="Fonts\IBMPlexMono-SemiBold.ttf" />
    <None Remove="Fonts\IBMPlexSans-Regular.ttf" />
    <None Remove="Fonts\IBMPlexSans-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="appsettings.Local.json" CopyToOutputDirectory="PreserveNewest" Condition="Exists('appsettings.Local.json')" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnapsackChallenge.Core\KnapsackChallenge.Core.csproj" />
    <ProjectReference Include="..\KnapsackChallenge.Data\KnapsackChallenge.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\IBMPlexMono-Regular.ttf" />
    <Resource Include="Fonts\IBMPlexMono-SemiBold.ttf" />
    <Resource Include="Fonts\IBMPlexSans-Regular.ttf" />
    <Resource Include="Fonts\IBMPlexSans-SemiBold.ttf" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
	</ItemGroup>

</Project>