<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnapsackChallenge.Common\KnapsackChallenge.Common.csproj" />
    <ProjectReference Include="..\KnapsackChallenge.Core\KnapsackChallenge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Local.json" CopyToOutputDirectory="PreserveNewest" Condition="Exists('appsettings.Local.json')" />
  </ItemGroup>

</Project>